### ISSUE TITLE
Copying a Bicep file equivalent for a resource

### ISSUE THREAD

**Issue by ucheNkadiCode** [microsoft/vscode-azureresourcegroups#138]
Based on feedback in https://github.com/Azure/bicep/issues/6256 - @majorku5anagi
Related to #139 

It would be great if a user could right click on a resource and then select "Copy as Bicep".

What this would do is:
- Grab this resource's `resource id` 
- Run Bicep: Insert snippet from resource
- Paste the output into this command into the user's clipboard.
- The user can now press Ctrl + V to paste this output.

We should **only show this option if Bicep is installed**.

Tagging @alex-frankel as well.

**Comment by majorku5anagi** [comment]
@ucheNkadiCode I would like to add maybe additional option:

- Import Bicep code in active window 
 
This way you can cherry pick and append (pile up) several resources that you want to manage into one single bicep file instead of separate files. It's the same as if you are repeatedly doing **Bicep: Insert** snippet manually.

Also, can this issue be moved to backlog candidate?

**Comment by majorku5anagi** [comment]
> Oh I see what you mean, like a "Copy as Bicep Code" button. I like that better honestly. This would make it such that a user could copy multiple items to their clipboard and then paste them all throughout a Bicep File

Either in a clipboard manner or just scrolling up & down through Az Resource Manager Extension, right clicking and choosing to directly insert the code in currently opened window... like cherry picking

**Comment by fiveisprime** [comment]
Hey friends, this is something that you'll be able to add from the Bicep extension once the new experience is shipped. I'm going to close this and I'll follow up with a bit more guidance on how to make this work.
