### ISSUE TITLE
Focus view

### ISSUE THREAD

**Issue by alexweininger** [microsoft/vscode-azureresourcegroups#179]

**Comment by bwateratmsft** [comment]
Including some workspace stickiness using the `workspaceState` memento!

**Comment by alexweininger** [comment]
@bwateratmsft We think it's ok to store the resource id as a workspace setting, was there another reason you wanted to use a `workspaceState` momento for this?

**Comment by bwateratmsft** [comment]
Storing it as a workspace setting means it gets checked in. The subscription ID, resource group name, and resource name are thus checked in, which is not desirable. Most people would consider them private information, and would not want them to be checked in.

**Comment by nturinski** [comment]
We have had this behavior for App Service and Functions for deployments for the last 5 years without any user feedback to indicate otherwise.  I don't know the entire details, but there was a bit of an issue with event listening with memento.

As for the Azure id being in the `.vscode` settings, we did kind of consider this to be a feature because this would allow resources to be sticky per workspace.  If you clone your repo down from another machine, you'd have the focused project view still (assuming those resources exist).

FWIW:
https://docs.microsoft.com/en-us/answers/questions/340725/is-subscription-id-personal-or-should-be-kept-priv.html#:~:text=In%20your%20case%20it%20is,are%20the%20users%20%2F%20owners%20etc.
https://stackoverflow.com/questions/45661109/are-azure-subscription-id-aad-tenant-id-and-aad-app-client-id-considered-secre

**Comment by bwateratmsft** [comment]
Discussed offline yesterday. One approach is to start out with using the `workspaceState` memento, and if people ask for change, switch to workspace settings. If started from the other direction, we would not be able to remove the data from their already-committed files.

**Comment by alexweininger** [comment]
Closed by #186
