### ISSUE TITLE
File doesn't stay "dirty" after a cancel/error

### ISSUE THREAD

**Issue by v-xinda** [microsoft/vscode-azureresourcegroups#19]
**OS:** All
**Build Version:** 20200612.3
**Repro Steps:**
1. Create a new resource group. 
2. Right click this resource group --> Click Edit Tags... .
3. Edit a tag --> CTRL+S --> Cancel --> Close the tags.jsonc. 
4. Click Edit Tags... again.

**Expect:**
It shows the original content.
![image](https://user-images.githubusercontent.com/57662131/84625776-855fa280-af16-11ea-8800-5607a1a457cd.png)

**Actual:**
It shows the edited content.
![image](https://user-images.githubusercontent.com/57662131/84626091-1898d800-af17-11ea-9e1a-cbf281b90efa.png)

**More Info:**
This issue reproduces for clicking "×".
![image](https://user-images.githubusercontent.com/57662131/84626813-5f3b0200-af18-11ea-818d-d198dc9e265f.png)

**Comment by EricJizbaMSFT** [comment]
The real problem here is the "dirty" state of the file. The tags _are not_ updated in Azure when a users clicks cancel (you can verify by viewing the tags in the portal), but the file _does_ goes from a dirty state to a saved state:

Dirty (with a circle):
<img width="344" alt="Screen Shot 2020-06-17 at 6 08 45 PM" src="https://user-images.githubusercontent.com/11282622/84966242-dd88d700-b0c5-11ea-8ad2-5a6961c1eb61.png">

Saved (with an x):
<img width="342" alt="Screen Shot 2020-06-17 at 6 08 51 PM" src="https://user-images.githubusercontent.com/11282622/84966249-e37eb800-b0c5-11ea-9e57-02b4718318c1.png">

Ideally the file would stay in a "dirty" state when a user cancels since the tags aren't actually updated in Azure. Unfortunately, that's easier said than done 😅

The same behavior occurs if there's an error instead of the user cancelling.
