### ISSUE TITLE
There are no "Create Function App in Azure..." and "Create Function App in Azure... (Advanced)" actions in context menu

### ISSUE THREAD

**Issue by v-ruizh** [microsoft/vscode-azureresourcegroups#195]
**OS:** All
**Azure Resource Extension Build Version:** 20220420.34 (unified)
**Azure Function Extension build Version:** 20220421.1 (unified)
**Regression:** Not a regression

**Repro Steps:**
1. Navigate to Azure Resources view, right click the subscription node.
2. Check whether there are "Create Function App in Azure..." and "Create Function App in Azure... (Advanced)" actions or not.

**Expect:**
There are "Create Function App in Azure..." and "Create Function App in Azure... (Advanced)" actions.

**Actual:**
There are no "Create Function App in Azure..." and "Create Function App in Azure... (Advanced)" actions.
![image](https://user-images.githubusercontent.com/45614674/164445437-8dbe57a4-f518-4477-a878-2136910a5251.png)

**More Info:**
There is "Create Function App in Azure..." action when clicking "Create Resource..." button.
![image](https://user-images.githubusercontent.com/45614674/164446408-1f805339-2ca5-4977-a6df-130c9ddea483.png)

**Comment by alexweininger** [comment]
Here is the expected context menu, regardless of what other extensions are installed. This has been fixed in #190. I'll be updating the OneNote soon with expected context menu items.

<img width="392" alt="image" src="https://user-images.githubusercontent.com/12476526/164511677-d01d80aa-143b-4ad4-96dd-36e54e8cbe9d.png">
