### ISSUE TITLE
All resource groups show in the "Resources" tree view after refreshing it 

### ISSUE THREAD

**Issue by v-xinda** [microsoft/vscode-azureresourcegroups#277]
**OS:** M1 & Win10
**Azure Resource Extension Build Version:** 20220522.1

**Repro Steps:**

1. Make sure the resource groups by Resource Group.
2. Click the "Focus this Group" icon to focus a resource group -> Refresh "Resources" tree view.
3. Check whether the focused resource group shows in the "Resources" tree view.

**Expect:**
Only the focused resource group shows in the "Resources" tree view.
![image](https://user-images.githubusercontent.com/57662131/169805589-ed8b1a58-9381-43fd-981e-6785c66fa6f2.png)

**Actual:**
1. All resource groups show in the "Resources" tree view.
2. The icon of the previous focused resource group still is "Unfocus Group".
![image](https://user-images.githubusercontent.com/57662131/169805856-2e875dd6-e473-4727-8551-f71d70c8df71.png)

**Comment by bwateratmsft** [comment]
We should fix this before //Build. Focusing on groups is one of our highlight features.

**Comment by alexweininger** [comment]
It's happening because the focusedGroupId is different from the id of the tree item after refreshing. The easiest solution might be to just use regex to ignore the resourceGroups part. This only reproduces with resource groups.

Example focusedGroupId: `/subscriptions/570117a0-fe37-4dfe-ae48-b692c1b25f70/resourceGroups/angular-basic-dotnet`
Example tree item id: `/subscriptions/570117a0-fe37-4dfe-ae48-b692c1b25f70/angular-basic-dotnet`

**Comment by bwateratmsft** [comment]
Does the grouping (i.e. the `/resourceGroups`) need to be in the `focusedGroupId`?

**Comment by alexweininger** [comment]
> Does the grouping (i.e. the `/resourceGroups`) need to be in the `focusedGroupId`?

> is there any reason the focusedGroupId should ever be different from the tree ID?

It shouldn't ever be different. I'm not sure why the tree ID is different after refreshing. That is the root cause. I'm a bit wary of changing how we generate tree IDs at this point.

https://github.com/microsoft/vscode-azureresourcegroups/compare/main...alex/focus-refresh might be the simplest solution. Not pretty, but it shouldn't break anything else.

**Comment by bwateratmsft** [comment]
Is the tree ID changing, or is the `focusedGroupId` just incorrect?

**Comment by alexweininger** [comment]
Ah, actually it was because we are using `Object.values` when we should have been using the `focusedGroupId` as a key.

I've updated the PR to show what I mean https://github.com/microsoft/vscode-azureresourcegroups/compare/main...alex/focus-refresh
