### ISSUE TITLE
The confirmation message is inconsistent when deleting a resource group from context menu and command palette

### ISSUE THREAD

**Issue by v-xinda** [microsoft/vscode-azureresourcegroups#308]
**OS:** Win10
**Azure Resource Extension Build Version:** 20220609.5
**Regression:** Not a regression

**Repro Steps:**
1. Right click a resource group -> Click "Delete Resource Group..." -> Check the confirmation message in the dialog.
2. F1 -> Click "Azure: Delete Resource Group..." -> Select the above selected resource group -> Check the confirmation message in the dialog.
3. Check whether the confirmation message is consistent between in the step1 and step 2.

**Expect:**
The confirmation message is consistent between in the step1 and step 2.

**Actual:**
The confirmation message is inconsistent between in the step1 and step 2.
![image](https://user-images.githubusercontent.com/57662131/173039698-38047a90-be7c-4ab0-914b-81da07f77c71.png)

**Comment by alexweininger** [comment]
Since this number is derived from the cached children, there are a few other cases where it breaks. For example, we're counting this UI-only tree item as a resource.

<img width="366" alt="image" src="https://user-images.githubusercontent.com/12476526/173156522-01d775bf-6125-46a5-af22-a4723c82cad3.png">

<img width="547" alt="image" src="https://user-images.githubusercontent.com/12476526/173156506-1a6f443a-6696-4fda-80a6-278ef0122e41.png">
