### ISSUE TITLE
The new added setting doesn't auto display in the application setting list when executing command "Azure Functions: Add New Setting..." from command palette

### ISSUE THREAD

**Issue by v-xinda** [microsoft/vscode-azureresourcegroups#487]
**OS:** Win10
**Build Version:** Azure Function v1.9.1-alpha.0 + Azure Resources v0.5.7-alpha.0

**Repro Steps:**
1. F1 -> Click "Azure Functions: Add New Setting..." -> Select a resource -> Enter a name -> Enter a value.
2. Check whether the new added setting auto displays in the application setting list.

**Expect:**
The new added setting auto displays in the application setting list.

**Actual:**
The new added setting doesn't auto display in the application setting list.

**More Info:**
1. This issue doesn't reproduce when executing "Add New Setting..." from context menu of the Application Settings node.
2. This issue also reproduces when executing "Azure Functions: Delete Setting..." from command palette.
3. There is no notification "Create XXX..." in the application setting list when executing command "Azure Functions: Add New Setting..." from command palette. As below:
<img width="416" alt="Screenshot 2022-12-23 at 16 38 52" src="https://user-images.githubusercontent.com/57662131/209308568-90b8ac87-a150-4985-82e8-a505bbcda0d6.png">
4. The application setting doesn't auto refresh after executing "Rename/Edit/Toggle as Slot Setting..." command from command palette.

**Comment by alexweininger** [comment]
Fixed by #496

**Comment by v-xinda** [comment]
@alexweininger  This issue also reproduces on the latest build 20230106.42. 
**Repro Steps:** 
Expand the Application setting node -> Execute "Add New Setting..." from command palette.

This issue doesn't reproduce if don't expand the Application setting node to create a new setting by executing "Add New Setting..." from command palette.
**Don't Repro Steps:**
Create a new function app (Don't expand the Application setting node) -> Execute "Add New Setting..." from command palette.

**Comment by v-xinda** [comment]
The new created **slot** doesn't auto display under the Slot node if expand the Slot node previously -> then create a new slot by executing "Create Slot..." from command palette.

**Comment by alexweininger** [comment]
This is happening because until now, the tree item picker could return cached tree nodes if nodes had already been shown on the tree UI. Now it always returns new tree nodes that aren't the same as any tree nodes visible on the tree.
 
For v1.5 extensions a band aid fix is to try to translate the picked node into a node that we already know about before giving it back to the client. This isn’t a sustainable solution as it requires access to the branch item cache, which v2 client extensions won’t have.

For v2 extensions, I’m not sure we can support this type of feature from the command palette unless we add caching. So maybe v2 clients should just refresh the whole tree in this case and not worry about incrementally updating the tree UI.

**Comment by alexweininger** [comment]
@v-xinda can you verify that this is fixed on the latest build of the `api-v2` branch?

**Comment by v-xinda** [comment]
@alexweininger  Verified this issue on the resource group latest build 20230112.10, it doesn't reproduce now.

**Comment by alexweininger** [comment]
@v-xinda thank you!
