### ISSUE TITLE
All of the locations show in the list after executing "Azure Static Web Apps: Open in GitHub" from command palette if the resources group by Location previously 

### ISSUE THREAD

**Issue by v-xinda** [microsoft/vscode-azureresourcegroups#574]
**OS:** Win 10
**Resource Group Build Version:** 20230214.5
**Static Web App Build Version:** v0.11.4

**Repro Steps:**

1. Make sure the resources group by Location.
2. F1 -> Click "Azure Static Web Apps: Open in GitHub".
3. Check Whether only the static web apps show in the list.

**Expect:**
Only the static web apps show in the list.
![image](https://user-images.githubusercontent.com/57662131/218977410-8589d71d-9396-44a8-a9dd-e25994016276.png)

**Actual:**
All of the locations show in the list.
![image](https://user-images.githubusercontent.com/57662131/218977884-6a7189b8-8cbc-4e14-957d-49117bc55f6f.png)

**More Info:** 

1. This issue also reproduces after the resources group by Resource Group or ARM Tag.
2. This issue doesn't reproduce after the resources group by Resource Type.
3. This issue also reproduces when executing commands related Static Web App.

**Comment by bwateratmsft** [comment]
This is expected behavior. We know based on the command being executed that we're looking for a static web app, so when grouping is by resource type, we can immediately select the SWA group. But when grouping is by location, RG, or ARM tag, we have to ask, since the apps could be in any of them, and we don't look more than one layer deep at a time.
