### ISSUE TITLE
[Suggestion] Add the "Other" option to select in "Review Issues" list

### ISSUE THREAD

**Issue by v-ruizh** [microsoft/vscode-azureresourcegroups#63]
**OS:** Win 10
**Build Version:** 20210218.10

**Repro Steps:**
1. Click "Review Issues" and "Report Issue" from "Help and Feedback" view.
2. Check the available Azure extensions in the list.

**Actual:**
There is an extra "Other" option in "Report Issue" list but not in "Review Issues" list.
![image](https://user-images.githubusercontent.com/45614674/108494931-188d7b00-72e3-11eb-8aa6-ddd538d5e07e.png)

**Suggestion:**
Add the "Other" option to select in "Review Issues" list.

**Comment by ejizba** [comment]
This is by design. During "Report Issue", we want people to file issues even if they're not sure which extension it's coming from, so we let them report it in the [azcode repo](https://github.com/Microsoft/azcode). However, we plan to move those issues to the _correct_ repo once we figure out which extension it applies to. So we don't want "Other" for "Review Issues" because we plan to move all issues out of that repo anyways
