### ISSUE TITLE
Resources not visible after selecting subscription.

### ISSUE THREAD

**Issue by RRanks** [microsoft/vscode-azureresourcegroups#780]
Hello,

New version seems to have issues finding resources when I am trying to deploy changes and a new function to my function app. I can find my subscription, but after selecting that. There are no resource groups returned at all.

I have manually rolled back and installed version 0.7.5 from a .vsix file and its working again. I can find my Resources. Seems new version 0.8.0 is not working correctly for me.

**Comment by nturinski** [comment]
Are you using a sovereign Azure such as China or Government?

**Comment by eliasrodeloso** [comment]
I'm having a similar issue with this. I can confirm this is happening with the 0.8.0 version of the extension and it's not happening on the 0.7.5. In my case I'm not using any sovereign Azure. And in my case the thrown error when this happens is as follows:

Timed out waiting for authentication provider to register.

A little more of information:

It only happens when you close and open VSCode again or when you have VSCode closed and go to the Azure menu in the left.

It is fixable if you downgrade to the v0.7.5 and refresh the resources submenu. If you upgrade to the 0.8.0 you still can see the resources until you close your VSCode instance.

**Comment by RRanks** [comment]
@nturinski and @MicroFish91 -  I am not in China or Government, it's a large US base energy companies' environment. I updated again to lastest version and still not working, back to 0.7.5.. and its fine.

**Comment by alexweininger** [comment]
@rranks we switched to a new authentication provider in 0.8.0. It could be that you're not signed into the right tenant/directory with the new provider. Please try using the "Sign in to Directory..." command and see if that fixes the issue.
