### ISSUE TITLE
Canceling deleting one resource group terminates others deleting when deleting multiple resource groups

### ISSUE THREAD

**Issue by v-dantch** [microsoft/vscode-azureresourcegroups#9]
**OS:** Windows
**Build Version:** [20200414.1](https://dev.azure.com/ms-azuretools/AzCode/_build/results?buildId=17759&view=results)
**Regression:** Not a Regression

**Repro Steps:**
1. Select multiple resource groups --> Select "Delete...".
![image](https://user-images.githubusercontent.com/34729092/79309432-dcec8c80-7f2c-11ea-9883-0c9128db37a6.png)
2. Select "Cancel" when asked to delete the 1st one.
![image](https://user-images.githubusercontent.com/34729092/79309661-394fac00-7f2d-11ea-822b-8bceefabbe64.png)

**Expect:**
Cancel to delete the 1st one, and it won't affect other resource groups.

**Actual:**
Canceling one resource group terminates deleting multiple resources groups.

**Comment by EricJizbaMSFT** [comment]
This is by design. For example, if they selected 20 resource groups, we're going to prompt them 20 times. That would be really annoying if we made them click "Cancel" 20 times if they wanted to cancel all of them. On the flip side, if they only wanted to cancel one of them, all they have to do is re-select the other ones and re-start the delete operation. That seems much more reasonable to me

**Comment by v-dantch** [comment]
Got it. Thanks for your sharing. 
How about adding a "Delete All" button when deleting multiple resource groups?

**Comment by EricJizbaMSFT** [comment]
I see what you're saying, but we don't want to make it _too_ easy to delete stuff. Deleting something cannot be un-done and we want to make sure people actually want to delete each resource group. I'd prefer to wait for people to ask for something like that before adding it

**Comment by v-dantch** [comment]
Got it.
